# Generated by Django 4.2 on 2024-02-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_created_date_category_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
